### ISSUE TITLE
[Chrome Headless] - Run Local

### ISSUE THREAD

**Issue by pavei** [ahll/whatsapp-web-botframework#1]
Hi,

Do you imagine how can i use Chrome Headless to use your bot?

Att,

**Comment by ahll** [comment]
Hi
    If you could get Login to web whatsaap by using  Chrome Headless, I will try to run bot in  Chrome Headless. The main problem is that I am not sure those websockets of whatsapp and my bot will woking .
Good day

**Comment by pavei** [comment]
I found this https://github.com/sarfraznawaz2005/whatspup it cloud be one way to do the work

**Comment by ahll** [comment]
How about https://github.com/GoogleChrome/puppeteer

**Comment by mosaw** [comment]
hi @ahll 
sorry for asking here but does  this api works  till now 
I can get the sms code and pass but I canot login 
github*com/ahll/Chat-API-NET

**Comment by ahll** [comment]
WhatsApp will ban the number if you do login many times
